### ISSUE TITLE
Relaxed ref/partial ordering shows invalid syntax

### ISSUE THREAD

**Issue by john-h-k** [alugili/CSharp8CheatSheet#1]
It shows `public ref partial class` which is illegal. `public ref partial struct` might of been intended?

**Comment by alugili** [comment]
thank you i have write the cheat before long time. i will check it out and if it a problem i will fix it.

**Comment by alugili** [comment]
Thank you I will correct it and upate the cheat.

**Comment by alugili** [comment]
fixed! class changed to struct.
